### PR TITLE
Make kalibr code lighter

### PR DESCRIPTION
**Pull request by v-mehta**
Removed SM, catkin_simple and suitesparse out of Kalibr repo to build the package lighter and faster.

### CODE REVIEW

**Comment by efernandez** [comment]
From https://github.com/clearpathrobotics/kalibr/tree/make-kalibr-code-lighter I see you still keep a few folders/packages. For example, `opencv2_catkin`. Could we remove that one, so everything uses OpenCV3.

Not sure about the other packages, we probably need them.

Other than this, :+1:

**Comment by v-mehta** [comment]
Will try that out. We have 9 subpackages which depend on that package so will update them. Similar can be done for Eigen and suitesparse. I would like to know what is the right way to use suitesparse though. We have two different ways used in g2o and gtsam IIRC.

**Comment by v-mehta** [comment]
Got rid of opencv_catkin package in the last commit.

**Comment by servos** [comment]
:+1:

**Pull request merged**
